
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: 
        context: ./frontend
        provenance: false
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      #- CORS_ORIGIN=*
    depends_on:
      - backend
